Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "container"
  config.vm.network "private_network", ip: "192.168.56.20"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
  end
end